### ISSUE TITLE
Data Management - Fix Pagination in Browse Tab

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#158]
Number of visible rows per page is getting down to 3, when the amount of pages is high. Pagination has to be fixed.
<img width="692" alt="screenshot at nov 16 13-38-55" src="https://cloud.githubusercontent.com/assets/5213372/11180992/7c7e4daa-8c67-11e5-85a4-76fcf12f2afd.png">

**Comment by edgarf** [comment]
(This is in Data Management, after you select one of the object which has many entries, you can try selecting "Student")

**Comment by ciprogrammer** [comment]
Please let me know if we need to refactor this beyond the change that was applied and we agreed was a good solution for the time being.
