### ISSUE TITLE
Creating event logging functionality

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#159]
A new database table should created to track actions done by the EASOl Dashboard users.
For now the following actions should be tracked:

Functions | Saved Meta data
------------ | -------------
Login | Date-time, IP Address, User
Flex Reports (Create) | Date-time, IP Address, User, Flex Report ID
Flex Reports (Edit) | Date-time, IP Address, User, Flex Report ID
Flex Reports (Delete) | Date-time, IP Address, User, Flex Report ID
Data Management (Data Upload) | Date-time, IP Address, User, Object, Imported file name, number of inserted/updated/deleted/failed rows

**Comment by tarlles10** [comment]
To fix it I increased the space in OldValue and NewValue fields on the table EASEL.Logs
