### ISSUE TITLE
Find out why is there a difference between Attendance results in different views

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#186]
Student/Attendance -  http://prntscr.com/94fy6g
Attendance - http://prntscr.com/94fye1

The data is different here. We need to found what is the difference and decide where is the correct data.

**Comment by ciprogrammer** [comment]
I dont understand this request. The 2nd screenshot is from outdated code and the two screenshots show dissimilar students. Please advise.

**Comment by ciprogrammer** [comment]
I am passing this back because there is insufficient data available on the db schema, re: table relationships/pk/fk/join columns, to decipher how to obtain the records requested. My suggestion is to recruit a database admin to deal with this issue.
