### ISSUE TITLE
Data Management - Add Data/Objects/Assosiation filtration.

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#206]
Currently we have a big number of objects in each of  the sections - http://prntscr.com/96b9o1
This is why we need to add an input field under the heading (title) of the section and allow users to filter (dynamically) by title of the object. 
Filteration should be done on the client side. You can use the same mechanism used in Content Search, the facet filtration - http://prntscr.com/96ba1t

**Comment by ciprogrammer** [comment]
Is this supposed to be done on objects only or objects,associations,types and descriptors?

**Comment by edgarf** [comment]
@ciprogrammer, there's an issue when I tap on "Show All" button. On the first load not all fields are there in the list and tapping this button the filtration field disappears.

**Comment by ciprogrammer** [comment]
Fixed and pushed to steve.206
