### ISSUE TITLE
Research: Remove WIDGET tool + Add new Field on Student filtering

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#221]
We need to finally remove the remaining Widget implementation from the remaining controllers. It seems to be
- [ ] Student List
- [ ] Cohorts
- [ ] Flex Reports

Please review and let us know how much time do you think it would take to remove it from there?

I also have noticed that there are some controllers, which are not used in the code. For example - "Schools" and "Admin". Could you please check if those are not used?

Once we remove the Widget from "Student" list we should do the following - 
- [ ] Add ability to dynamically search by the full user name (first + last name). In other words add an input field for client side user filtering by full name.

**Comment by regiscamimura** [comment]
I would say something around 12h to remove the widget implementation, including the clean up of existing libraries, directories, models (i.e., the removal of classes that are not going to be used anymore). It also includes the dynamic search for the Student list.

I checked the Admin and Schools controllers. Admin we can remove, it does nothing. For Schools, we can remove the "index" method, but it's being used just to present the dropdown for school selection after an admin user gets logged in. It's not the best workflow though, I would move that to the core controller, so let me know if you want me to do that. That would be around 5h.

**Comment by edgarf** [comment]
@regiscamimura, thanks for that. Let's do this then
1) Remove widget from "Students" list
2) Add new field in Student list 
3) Remove widget tool from Cohorts.

Thank you!

**Comment by edgarf** [comment]
@regiscamimura I assume we don't have the widget tool in Cohorts and Students, right?
