### ISSUE TITLE
Flex report preview popup never goes away with "bad" SQL

### ISSUE THREAD

**Issue by jamessun** [EASOL/easol#253]
Steps to reproduce: 
1. Visit [http://easol-dev-staging.azurewebsites.net/reports/edit/28](http://easol-dev-staging.azurewebsites.net/reports/edit/28) (or create a new Flex Report with the SQL listed below)
2. Press Preview button.
3. Popup appears. Spinner spins indefinitely.

Here's the SQL/Command Text for the Flex Report:
```
SELECT *
FROM edfi.Student
WHERE Student.LastSurname LIKE 'S%'
ORDER BY LastSurname
```
There is an issue right now with an ORDER BY clause in the Flex Report SQL query.

**Comment by edgarf** [comment]
Seems like the ORDER By is causing the issue. @regiscamimura - I see the ORDER BY is having the issue even in previous code, the one we had before Dynamic variables.
