### ISSUE TITLE
Flex Report with SQL that has last line commented out isn't handled properly

### ISSUE THREAD

**Issue by jamessun** [EASOL/easol#254]
Steps to reproduce: 

1. Visit http://easol-dev-staging.azurewebsites.net/reports/view/29 to view the results of a predefined query (or create a new Flex Report with the SQL listed below)

```
SELECT StudentUSI
FROM edfi.Student /* Comment */
WHERE Student.LastSurname LIKE 'S%' -- Comment
-- AND Student.Firstname LIKE 'S%'
```

I get the following error:

> Error Number: 42000/102
> 
> [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near 'S%'.
> 
> SELECT count(*) as tot FROM (SELECT StudentUSI FROM edfi.Student /* Comment */ WHERE Student.LastSurname LIKE 'S%' -- Comment -- AND Student.Firstname LIKE 'S%') as b
> 
> Filename: D:/home/site/wwwroot/application/widgets/DataTableWidget/DataTableWidget.php
> 
> Line Number: 152
> 

Looks like the issue is the final line in the SQL which is commented out.

**Comment by jamessun** [comment]
This seems to work fine in EASOL-dev.

Flex Report CommandText is:
```
SELECT StudentUSI
FROM edfi.Student /* Comment */
WHERE Student.LastSurname LIKE 'S%' -- Comment
-- AND Student.Firstname LIKE 'S%'
```
See http://easol-dev.azurewebsites.net/reports/view/57

**Comment by edgarf** [comment]
Good, I assume we can close it, right?
