### ISSUE TITLE
Can't use TOP in SELECT clause for Flex Report

### ISSUE THREAD

**Issue by jamessun** [EASOL/easol#255]
Steps to reproduce: 

1. Visit http://easol-dev-staging.azurewebsites.net/reports/view/30 to view the results of a predefined query (or create a new Flex Report with the SQL listed below)

```
SELECT TOP 1 StudentUSI
FROM edfi.Student
```

I get the following error:

> Error Number: 42000/10741
> 
> [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]A TOP can not be used in the same query or sub-query as a OFFSET.
> 
> SELECT TOP 1 StudentUSI FROM edfi.Student ORDER BY StudentUSI OFFSET 0 ROWS FETCH NEXT 25 ROWS ONLY
> 
> Filename: D:/home/site/wwwroot/application/widgets/DataTableWidget/DataTableWidget.php
> 
> Line Number: 178

**Comment by jamessun** [comment]
SELECT TOP seems to work in EASOL-dev. The following CommandText works:
```
SELECT TOP 2 LastSurname
FROM edfi.Student
ORDER BY LastSurname
```
See http://easol-dev.azurewebsites.net/reports/view/56

**Comment by edgarf** [comment]
Perfect, shall we close this?
