### ISSUE TITLE
Flex Reports - ORDER BY ignored when report is run

### ISSUE THREAD

**Issue by jamessun** [EASOL/easol#265]
Take a look at this Flex Report, http://easol-dev.azurewebsites.net/reports/view/62

Here's the SQL:
```
SELECT 
  Firstname
  , COUNT(*) AS cnt
FROM edfi.Student
WHERE $filter
GROUP BY Firstname
ORDER BY 2 DESC
```
When I preview the report from the Edit page, http://easol-dev.azurewebsites.net/reports/edit/62, the ORDER BY is respected.

When I view the results of the report, the results are listed in ascending alpha order by Firstname.

**Comment by edgarf** [comment]
Hi James, thank you. That's a good find. @regiscamimura, would you mind looking into it?
