### ISSUE TITLE
Responsive problem on Table views

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#292]
When the number of columns is higher, the table hovers over the left navigation menu. Let's apply some responsiveness rules.

**Comment by regiscamimura** [comment]
@edgarf I got it done, the tables will allow horizontal scrolling from now on. Be aware that's not the only responsiveness handling option. We can easily make columns that would overflow are collapsed, and an [+] icon is added so when clicking on it, it would expand: https://datatables.net/extensions/responsive/examples/styling/bootstrap.html

We can also make the details to open in a modal window: https://datatables.net/extensions/responsive/examples/display-types/bootstrap-modal.html -- click the [+] icon to see how it works

We can also allow the user to pick which columns will be visible: https://datatables.net/extensions/responsive/examples/column-control/column-visibility.html -- click the **column visibility** button.

Keep in mind that we can also add a feature so the user can drag/drop columns to change its order, if that would help visualization. 

All those options are easy to implement, just let me know if they want more responsiveness features on the tables.

**Comment by edgarf** [comment]
Hey Regis,
So I've been testing this feature and here are the comments
1) If the "Column visibility" wouldn't take more than 1 hours to be integrated - let's add it.
2) Currently "Responsive" mode on table view works well, however on chart related pages the first row jumps away (see screenshot below) URL - http://easol-dev.azurewebsites.net/reports/view/37
![image](https://cloud.githubusercontent.com/assets/5213372/14077649/728bcfa0-f4f6-11e5-832f-9274f66c4fc7.png)
3) Clicking on Pie/Bar Chart Slice/Bar doesn't filter out the list elements (it was working before this commit).

**Comment by regiscamimura** [comment]
@edgarf Fixed the issues and added column visibility button

**Comment by edgarf** [comment]
@regiscamimura - actually, I have noticed one issue with other tables. See below, the tables gets mixed up like that. However, when the "Table" kind of results is selected, after refreshing they get back to a proper place.
![image](https://cloud.githubusercontent.com/assets/5213372/14168161/38a327b8-f729-11e5-9e2f-a7f461ab1d24.png)

**Comment by regiscamimura** [comment]
fixed.

**Comment by edgarf** [comment]
@regiscamimura, thanks. A few small issues
1. The table header is still "shrinked" on the form (screenshot below).
![image](https://cloud.githubusercontent.com/assets/5213372/14199806/02e7416e-f7f0-11e5-82cf-29f4704ce0f4.png)

2. On the report table view, it seems like there is always a horizontal scroller, doesn't matter how many columns are visible - https://www.dropbox.com/s/9kveupadsm5skfc/easol_horizontal_scroll_issue.mp4?dl=0 (video screencast)

**Comment by regiscamimura** [comment]
fixed. Can you please try again?

**Comment by edgarf** [comment]
Solved! Thank you/
