### ISSUE TITLE
Put pie chart labels outside the pie

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#296]
Let's try putting the pie-chart labels outside the pie itself. Example is here - nvd3.org/examples/pie.html

**Comment by regiscamimura** [comment]
@edgarf done. pushed to branch 266.

**Comment by edgarf** [comment]
@regiscamimura - I noticed that now you can't tap on a Pie Slice again to de-select the selection and "un-filter" the results below.  (Please check the same with bar-charts)

**Comment by regiscamimura** [comment]
Fixed.

**Comment by edgarf** [comment]
It works, thanks!
