### ISSUE TITLE
Minor issue with Spaces

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#307]
We have noticed, that if a variable has a space when defining one for aggregation, the "click -> drill_down" is not working.

The console says:
```Uncaught Error: Syntax error, unrecognized expression: thead th[data-variable=Proficiency Rating]Sizzle.error @ jquery.js:1458Sizzle.tokenize @ jquery.js:2075Sizzle @ jquery.js:821jQuery.fn.extend.find @ jquery.js:2695chart_filter @ charts.js:106(anonymous function) @ charts.js:80(anonymous function) @ d3.js:343```

Would it be possible to resolve it and allow users enter data with spaces?

**Comment by edgarf** [comment]
@regiscamimura, also the same problem with "Links" section. How should I write it down if the column is called "Student ID" and the format of our current link system is ```/path/to/url/$variable```

**Comment by regiscamimura** [comment]
@edgarf Just got it fixed. Pushed to branch 307. Regarding the links, it works just fine if you do something like `/path/to/url/$Student ID`

**Comment by edgarf** [comment]
It works, thank you!
