### ISSUE TITLE
Overlay intro disappeared

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#314]
We had an overlay intro with descriptions on how to use the system when user logs in first time (using cookies to define that). It doesn't appear anymore. @regiscamimura, could you please investigate?

**Comment by regiscamimura** [comment]
@edgarf indeed there was a minor issue with the js library path. I corrected the path and it's working again. I pushed directly to development branch, since it was really minor, no actual code change. Is that ok?

**Comment by edgarf** [comment]
Great! It works now, thank you.
