### ISSUE TITLE
Minor Fixes

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#350]
@regiscamimura, a few things
- [x] When you are on the assessment view and click on a Student, you should get into Student detail view with Assessments tab open
- [x] When you are on Attendance view and click on a student, you should get to the student view with "Attendance" tab opened
- [ ] In both situations above when I click on student details and go to Assessment or Attendance tabs, the information there is not the same as it was on the list views. Please make sure the information is valid there.

**Comment by regiscamimura** [comment]
@edgarf I did the change so both the links goes to the proper tab. Regarding the missmatching between the views:

1. Between the assessment view and the assessment tab in student view, I can't really see anything going wrong. They seem to match, and the query itself, although different, should produce the same results. Am I missing something? Do you have any example of missmatch?

2. For the Attendence view, yes, we do have a missmatching. Thing is that when you look at the Attendence view, it will look for records on the table for StudentSchoolAttendanceEvent, but when you look at the attendence tab in student view, it will look for records on the table for  StudentSectionAttendanceEvent. So one is about school attendance, the other is about section attendance. 
The attendance view ignores any references to section attendances and just look straight to school attendances.
The student view > attendance tab looks for section attendances and ignores school attendances though.
I not sure what's the difference between those in the real world, but well, how could a student have an absence record for a school, but a presence record in a section for the same day? Not sure, but it seems a possible situation in the DB layer, cause an attendence record for a school does not relates with an attendance to a section. Thoughts?

**Comment by edgarf** [comment]
Hey @regiscamimura, thanks for the update on that.

1. Assesments - right seems to be working, might be my bad. Though please come back to that other issue, where details view of assessments is not equal to list view.

2. Attendance - I will ask people on our end and let you know.

**Comment by edgarf** [comment]
Here is the difference about Attendance

**StudentSectionAttendanceEvent.**
 This is the attendance for the Section of class for a day, 
 example: a student might have 4 clasese... Math, Reading, Gym, Geography.
 There will be four attendance records for that student for each class.
 GradeSchool will not have any section attendance.
    
**StudentSectionAttendanceEvent.**
 This is the final tally for day... ie.. present,excused, unexcused.
 Gradeschool will have just this.

Results: For the Student Attendance Tab, let's make it the same as /Attendance (as I understand we will convert it to School Attendance, right?). However, don't delete current implementation with sections, we might use it later.

Thanks!

**Comment by regiscamimura** [comment]
@edgarf Ok, I'll make the Student Attendance Tab to look for records in StudentSchoolAttendanceEvent, but need to know how to display the data. I mean, currently, it shows a table with columns for period, course code, section. Now, we're going to just display the final tally for the day, what to display? Should it not be a table, but just a summary of how many present/tardy/absence events the student got in total? Or should it be a table, and in that case, we would have a line for the total of present/tardy/absence for each year? Or maybe year and term? Should we have filters? 

Another option is to have a table with record for each DAY. So we would have columns for "date", "term", and "type". Type would be present, tardy or absence.

Please share your thoughts.

**Comment by edgarf** [comment]
Hi @regiscamimura your suggestion is logical. Let's maybe have a list of all days with ability to select start-end period and also 1 additional line to show "Sum" of all kind of attendances. How much effort would be required for that? (Please also make sure we won't delete the previous view)

**Comment by regiscamimura** [comment]
@edgarf Regarding the additional line to show the sum, the datatables already show how many records there are, so it's probably better to just put it more visible, at top instead of bottom. and I'm assuming you will want a column for "type". The effort is around 4h or work. I'll wait for confirmation.

**Comment by edgarf** [comment]
What if we wouldn't add the filter with start/end dates? And just show the list of attendance day-by-day? What's the effort here? We might need to iterate it in a few times.

**Comment by edgarf** [comment]
@regiscamimura  - Let me know if that's viable.

**Comment by regiscamimura** [comment]
@edgarf yes, that's doable. removing the start/end date filters will reduce the effort in 1h, so estimate is 3h.

**Comment by edgarf** [comment]
Let's do it then.  (Without removing all code please).

**Comment by regiscamimura** [comment]
@edgarf this it done and pushed to 350 FYI

**Comment by edgarf** [comment]
Thanks! Will check tomorrow
