### ISSUE TITLE
Add ability to select Term in Attendance View

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#351]
Add ability to select Term in Attendance View. Only allow to select from the existing ones in the dataset below.

**Comment by regiscamimura** [comment]
@edgarf hmm I don't really get what field would "Term" be. There is no such column in the dataset below... would term be "present/excused/unexcused"?

**Comment by edgarf** [comment]
@regiscamimura Sorry for lack of information on this. I have meant "Term" as "Fall Semester", "Spring Semester". Can you check how the calculations are done now? Is the full SchoolYear taken?

Additionally, there is one more update (in the system in overall needed). It's not very clear what SchoolYear is in mind. For example if it says "2014", Does it mean 2013-2014 or 2014-2015? We have an assumption that it is YEAR - (YEAR+1), so in situation with 2014 (2014-2015). Could you please 1. Validate whether my thoughts are correct 2. Update labels on all filter options and dataset views to show the interval instead of 1 integer value? We'd like to do it without changing data in the db.

**Comment by regiscamimura** [comment]
@edgarf Done and pushed to 351

**Comment by regiscamimura** [comment]
@edgarf the SchoolYear piece is still pending though. Working on it.

**Comment by edgarf** [comment]
@regiscamimura - do you think you'd be able to push the rest of the task today? Thanks!

**Comment by regiscamimura** [comment]
@edgarf Before getting it done, I'm not much sure neither if 2014 means 2013-2014 or 2014-2015, and we need to get it figured out. For the attendance view, we have records which School Year is 2011, but the EventDate is from 2010, so it seems when you say 2011, you mean 2010-2011.

Also, in the table for StudentSchoolAssociation, we have records with SchoolYear being 2011, while the "EntryDate" is from 2010. So it seems that 2011 mean when the school year ends, so that would be 2010-2011.

Well, those are still assumptions I made just by looking over the data in the DB. Can we trust the data is correct? Can someone confirm my understanding?

**Comment by edgarf** [comment]
@regiscamimura -  sorry for not getting back to you sooner. Can you tell me whether you were looking into the easol-dev or easol-dev-staging2?

**Comment by regiscamimura** [comment]
@edgarf I was looking into easol-dev

**Comment by edgarf** [comment]
@regiscamimura - Let's do it like this - " $School_Year "-" ($School_Year+1)" I talked with people on our team and they asked to use this. easol-dev is using a little bit different ingestion process. So it should be good with the way proposed.

**Comment by edgarf** [comment]
@regiscamimura - let me know when we can do this.

**Comment by regiscamimura** [comment]
@edgarf This is done, and pushed to branch 329. The issue #329 it's related to year filter dropdowns so I put it together. Not sure if the analytics portion fits the changes (i.e., should we use year - year + 1 as labels on it?), so it's just skipped. Let me know your thoughts on this.

**Comment by edgarf** [comment]
Thank you, I will check re Analytics and let you know.

**Comment by edgarf** [comment]
@regiscamimura, thanks for the update. Let's also add this yea-year layout for all other places where it appears. For example here below:
![image](https://cloud.githubusercontent.com/assets/5213372/15892752/2969f524-2d84-11e6-8ca8-52389193e962.png)

**Comment by regiscamimura** [comment]
@edgarf You mean to make the "Year" column in the table below to also show 2011-2012 instead of just 2011?

**Comment by edgarf** [comment]
Correct. And everywhere else, where is it mentioned.

**Comment by regiscamimura** [comment]
@edgarf For the assessment views, we do have a filter for Year. But in that context, Year does not refers to a School Year, but to the "Version" column, so I'm not sure if using values like 2007-2008 would be appropriated here. Unless we also consider "Version" being 2007 to actually mean 2007-2008. Thoughts?

**Comment by regiscamimura** [comment]
@edgarf and regarding the analytics area, I see now that makes perfect sense to use the school year range like 2011-2012, so I pushed that to the branch 351.

**Comment by edgarf** [comment]
Hi @regiscamimura  - let's convert "Version" to the x-y combination too. Thank you!

**Comment by regiscamimura** [comment]
@edgarf Just did.

**Comment by regiscamimura** [comment]
@edgarf btw, branch 351 is merged with development, you should have no problem on merging back development with 351
